# Deployment settings
name: eqcms-email-service
componentsLabel: email-service
replicaCount: 1
namespace: cms

# App settings
secretName: eqsitecms-email-service-secret
containerPort: 8000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

metrics:
  enabled: true
  metricsPort: 9000
  interval: 30s

# Image settings
image: ghcr.io/igor-526/eqsitecms-email-service
imagePullSecertName: ghcr-secret
imageTag: latest

migration:
  command: ["uv", "run", "alembic", "-c", "alembic.ini", "upgrade", "head"]
  workingDir: /app/src

workers:
  - name: celery-worker
    command: ["uv", "run", "--no-sync", "celery", "-A", "workers.celery_app", "worker", "-Q", "email", "-l", "info"]
    replicas: 1